### ISSUE TITLE
Access to the "correct outward-facing faces"

### ISSUE THREAD

**Issue by MrTornado24** [SheldonTsui/GOF_NeurIPS2021#5]
Hi, thanks for your work and released code! Could you share the correct outward-facing faces so that we can train from scratch?

**Comment by SheldonTsui** [comment]
Hi, I have already provided them. Please refer to the pretrained models in README.

**Comment by MrTornado24** [comment]
Thanks for your answer. What I mean is the "correct outward-facing " images that you train with, rather than the pretrained model.

**Comment by SheldonTsui** [comment]
The "correct outward-facing faces" means the learned shapes are outward-facing, not inward-facing. This phenomenon is discussed in Sec4.2 of this paper "Campari: Camera-aware decomposed generative neural radiance fields". For the training images, we just use 2D images from BFM, CelebA, or Cats as presented in the paper.

**Comment by MrTornado24** [comment]
Thanks a lot. I am still confusing that if you just use the original dataset, what is the difference between training from an early pretrained model and "train from scratch"? What is the setup of the first 2k iterations to make sure that the correct outward-facing shape can be learned? Campari just states this problem but I am interested in how you solve it?

**Comment by SheldonTsui** [comment]
In the experiments, we find that the model trained on the original datasets **sometimes** learned "wrong" inward-facing shapes and **sometimes** learned "correct" outward-facing shapes. It's just like a random result. We don't find the control factor yet.
 However, we find that the model will keep the inward/outward property as the training goes, ie, the model will keep the correct outward-facing shape if starting from an outward-facing one. Therefore, in order to ensure the **final** correct outward-facing shape, the training of all models starts from an early pretrained model with the correct outward-facing faces.

**Comment by MrTornado24** [comment]
Thanks for your detailed explanation!
